var abilities = {
    'conoscenza_metalli_rocce' : {
        "attribute" : "IT",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Conoscenza Metalli e Rocce"
    },
    'conoscenza_mondo_animale' : {
        "attribute" : "[IT+PR]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Conoscenza del Mondo Animale"
    },
    'conoscenza_mondo_vegetale' : {
        "attribute" : "IT",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Conoscenza del Mondo Vegetale"
    },
    'cultura_generale' : {
        "attribute" : "[IT + PR]",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": null,
        "gradi1": null,
        "total": "max_children",
        "nome": "Cultura Generale"
    },
    'usi_e_costumi' : {
        "attribute" : null,
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": null,
        "gradi5_parent": "cultura_generale",
        "gradi3": 10,
        "gradi1": true,
        "nome": "Usi e Costumi"
    },
    'luoghi_e_vie' : {
        "attribute" : null,
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": null,
        "gradi5_parent": "cultura_generale",
        "gradi3": 10,
        "gradi1": true,
        "nome": "Luoghi e Vie"
    },
    'miti_e_leggende' : {
        "attribute" : null,
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": null,
        "gradi5_parent": "cultura_generale",
        "gradi3": 10,
        "gradi1": true,
        "nome": "Miti e Leggende"
    },
    'matematica' : {
        "attribute" : "IN",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Matematica"
    },
    'erudizione' : {
        "attribute" : "IN",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Erudizione"
    },
    'lavorare_metalli' : {
        "attribute" : "FR",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Lavorare Metalli"
    },
    'lavorare_legno' : {
        "attribute" : "FR",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Lavorare il Legno"
    },
    'lavorare_pietra' : {
        "attribute" : "FR",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Lavorare la Pietra"
    },
    'lavorare_pelli_tessuti' : {
        "attribute" : "AG",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Lavorare Pelli e Tessuti"
    },
    'colpire_alle_spalle' : {
        "attribute" : "PR",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Colpire alle Spalle"
    },
    'destrezza' : {
        "attribute" : "[PR + AG]",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Destrezza"
    },
    'inventare_capire_congegni' : {
        "attribute" : "[IT + IN]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Inventare / Capire Congegni"
    },
    'muoversi_silensiosamente' : {
        "attribute" : "[IT + PR]",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Muoversi Silenziosamente"
    },
    'Nascondersi' : {
        "attribute" : "IT",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Nascondersi"
    },
    'scas_costr_disatt_congegni' : {
        "attribute" : "[IT + AG]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Scass. / Costr. Disat. Congegni"
    },
    'scrittura_falsificazione' : {
        "attribute" : "[IN + AG]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Scrittura e Falsificazione"
    },
    'stordire' : {
        "attribute" : "[AG + PR]",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Stordire"
    },
    'travestimento_imitazione' : {
        "attribute" : "[IT + PR]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Travestimento e Imitazione"
    },
    'utilizzare_corde' : {
        "attribute" : "AG",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Utilizzare Corde"
    },
    'addestrare_animali' : {
        "attribute" : "PR",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Addestrare Animali",
    },
    'astronomia' : {
        "attribute" : "IT",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Astronomia",
    },
    'capacita_mondo_naturale' : {
        "attribute" : "IT",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Capacità nel Mondo Naturale",
    },
    'cavalcare' : {
        "attribute" : "[IT + AG]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Cavalcare",
    },
    'commerciare_valutare' : {
        "attribute" : "[IN + PR]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Commerciare e Valutare",
    },
    'navigare' : {
        "attribute" : "IT",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Navigare",
    },
    'segnalazione' : {
        "attribute" : "[IN + IT]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Segnalazione",
    },
    'seguire_tracce' : {
        "attribute" : "[IN + IT]",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Seguire Tracce",
    },
    'speleologia' : {
        "attribute" : "[IN + IT]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Speleologia",
    },
    'cantare' : {
        "attribute" : "[IT + PR]",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Cantare",
    },
    'contorsionismo' : {
        "attribute" : "2*AG + FR",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Contorsionismo",
    },
    'cucinare' : {
        "attribute" : "IT",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Cucinare"
    },
    'frenesia' : {
        "attribute" : "PR",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Frenesia",
    },
    'medicare' : {
        "attribute" : "[IN + IT]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Medicare",
    },
    'meditazione' : {
        "attribute" : "[IT + PR]",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Meditazione",
    },
    'oratoria' : {
        "attribute" : "PR",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Oratoria",
    },
    'suonare' : {
        "attribute" : "[AG + PR]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Suonare",
    },
    'autocontrollo_coraggio' : {
        "attribute" : "Disciplina",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Autocontrollo e Coraggio",
    },
    'comando_influenza' : {
        "attribute" : "Carisma",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Comando e Influenza",
    },
    'movimento_con_ingombri' : {
        "attribute" : "Movimento",
        "studio": null,
        "fixed_bonus": 30,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Movimento Con Ingombri",
    },
    'percezione' : {
        "attribute" : "IT + PR",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Percezione",
    },
    'potere' : {
        "attribute" : "Volontà",
        "studio": null,
        "fixed_bonus": 5,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Potere",
    },
    'resistenza' : {
        "attribute" : "Vita",
        "studio": null,
        "fixed_bonus": 55,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Resistenza",
    },
    'resistenza_ai_veleni' : {
        "attribute" : "3 * CO o CO",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Resistenza ai Veleni",
    },
    'resistenza_alle_malattie' : {
        "attribute" : "3 * CO o CO",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Resistenza alle Malattie",
    },
    'acrobazia' : {
        "attribute" : "AG",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Acrobazia",
    },
    'arrampicarsi' : {
        "attribute" : "AG",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Arrampicarsi",
    },
    'danzare' : {
        "attribute" : "[AG + IT]",
        "studio": 80,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Danzare",
    },
    'nuotare' : {
        "attribute" : "AG + FR",
        "studio": null,
        "fixed_bonus": null,
        "bonus_gradi": null,
        "gradi5": 10,
        "gradi3": 10,
        "gradi1": true,
        "nome": "Nuotare",
    },
};

